### ISSUE TITLE
(Examples) ERROR: LoadError: type Simulation has no field particles_to_save

### ISSUE THREAD

**Issue by ibordeu** [michaelwang314/SoftSquishyMatter.jl#41]
When trying to run the Example_ActiveBrownian.jl I get the error
ERROR: LoadError: type Simulation has no field particles_to_save (line 51).

I tried changing
simulation.particles_to_save = pgroup_all
by 
simulation.things_to_save = pgroup_all
but then I get the following error:

ERROR: LoadError: MethodError: Cannot `convert` an object of type Vector{Particle} to an object of type NamedTuple{(:particles, :bonds), Tuple{Vector{Particle}, Vector{Tuple{Particle, Particle}}}}
Closest candidates are:
  convert(::Type{NamedTuple{names, T}}, ::NamedTuple{names, T}) where {names, T<:Tuple} at namedtuple.jl:127
  convert(::Type{NamedTuple{names, T}}, ::NamedTuple{names, T} where T<:Tuple) where {names, T<:Tuple} at namedtuple.jl:130
  convert(::Type{T}, ::T) where T at essentials.jl:205
  ...

**Comment by michaelwang314** [comment]
@ibordeu Sorry for the late reply.  I haven't had a time to get back into this project.

I made some updates to the code way back but never got around to updating the example files.  Try `Simulation.things_to_save = (particles = pgroup_all, bonds = [])` if you have no harmonic bonds between particles.

**Comment by ibordeu** [comment]
Works peferct. Thanks!
